name: Publish create-vite-express package
on: 
  push:
    tags:
      - cli-v*
jobs:
  test:
    name: Run tests on npm build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn test
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 16
      - run: cd create-vite-express && yarn install && yarn build && npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
